workload: 'cluster-density'
uuid: 'a9ddd61b-d12e-4922-86a2-ea17354d80hh'
es_server: 'https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443'
es_index: 'ripsaw-kube-burner'
qps: 20
burst: 20
log_level: 'info'
timeout: '25m'
iterations: 5
churn: 'true'
churn_duration: 2m0s
churn_delay: 1h0m0s
churn_percent: 10 
alerting: 'true'
gc: 'true'
kubeconfig: |
  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CR...
      server: https://api.dummycluster.openshift.com:6443
    name: api-dummycluster-openshift-com:6443
