workload_template: 'cfg_delete_icni2_node_density2.yml'
scale_factor: 2
bfd_enabled: false
uuid: 'poiy761b-d12e-4922-86a2-ea17354d80hh'
kubeconfig: |
  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CR...
      server: https://api.dummycluster.openshift.com:6443
    name: api-dummycluster-openshift-com:6443
